# Generated by Django 5.0.1 on 2024-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
