# Generated by Django 5.0.1 on 2024-02-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_app', '0005_cart_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
